spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 815099873461-0f6ihlaj0nhhf5aus8r9q1amelc6ch32.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://db.gaotasxpjtdkcravtjzv.supabase.co:5432/postgres
    username: postgres
app:
  clientOAuth2TokenUrl: https://filipostermark.github.io/kmmk-frontend/#/oauth2/token
