spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 815099873461-ntqp372b2spo4rp95r7v8cjqi2k9n3bd.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5555/postgres
    username: kmmk
    password: kmmk
app:
  clientBaseUrl: http://localhost:5173
  clientOAuth2TokenUrl: http://localhost:5173/kmmk-frontend/#/oauth2/token
